

all:
	protoc -I=. --python_out=./python/ BC.proto
	cp ./python/BC_pb2.py .



#protoc -I=. --python_out=./python/ Companion.proto



	#python gen_companion_proto.py ../../src/out/sources/co/glassio/blackcoral/HandshakeResponse.java
